version: '3'
services:
  etcd:
    image: "quay.io/coreos/etcd"
    command:
    - sh
    - '-c'
    - >-
      /usr/local/bin/etcd --data-dir=/data
      --initial-advertise-peer-urls=http://$$(hostname -i):2380
      --name=node1 --listen-peer-urls=http://0.0.0.0:2380
      --advertise-client-urls=http://$$(hostname -i):2379
      --listen-client-urls http://0.0.0.0:2379 
      --initial-cluster node1=http://$$(hostname -i):2380
      --listen-client-urls http://0.0.0.0:2379
  ui:
    build: 
      context: .
      dockerfile: cmd/ui/Dockerfile
    depends_on:
    - etcd
    ports:
     - "8080:8080"
  controller:
    build: 
      context: .
      dockerfile: cmd/controller/Dockerfile
    depends_on:
    - etcd
  api: 
    build: 
      context: .
      dockerfile: cmd/apiserver/Dockerfile
    ports:
     - "8000:8000"
    depends_on:
    - etcd