version: '3'
services:
  controller:
    privileged: true
    build:
      context: .
      dockerfile: cmd/controller/Dockerfile
    networks:
      app_net:
        ipv4_address: 172.18.0.2
    volumes:
    - ./dhcpmanager.toml:/etc/dhcpmanager/dhcpmanager.toml
  apiserver:
    build:
      context: .
      dockerfile: cmd/apiserver/Dockerfile
    ports:
     - "8000:8000"
    networks:
      app_net:
        ipv4_address: 172.18.0.3
  etcd:
    image: "alfatraining/etcd3"
    networks:
      app_net:
        ipv4_address: 172.18.0.4
  dhcpd:
    image: "joebiellik/dhcpd"
    volumes:
    - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
    networks:
      app_net:
        ipv4_address: 172.18.0.5
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
