# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  deploy-container:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /go/src/github.com/kramergroup/dhcpmanager
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -f cmd/apiserver/Dockerfile -t kramergroup/dhcpmanager-apiserver .
      - run: docker push kramergroup/dhcpmanager-apiserver
      - run: docker build -f cmd/controller/Dockerfile -t kramergroup/dhcpmanager-controller .
      - run: docker push kramergroup/dhcpmanager-controller
      - run: docker build -f cmd/backend/Dockerfile -t kramergroup/dhcpmanager-ui-backend .
      - run: docker push kramergroup/dhcpmanager-ui-backend

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - deploy-container
